// <auto-generated />
using Liste.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Liste.DataAccess.Migrations
{
    [DbContext(typeof(ListeDbContext))]
    partial class ListeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Liste.Entities.SinifListesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Alani")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Okulu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Soyad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Yas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SinifListesis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "ömer",
                            Alani = "matematik",
                            Okulu = "ilkokul",
                            Soyad = "faruk",
                            Yas = 12
                        },
                        new
                        {
                            Id = 2,
                            Ad = "ahmet",
                            Alani = "türkçe",
                            Okulu = "lise",
                            Soyad = "veli",
                            Yas = 20
                        },
                        new
                        {
                            Id = 3,
                            Ad = "erman",
                            Alani = "türkçe",
                            Okulu = "lise",
                            Soyad = "ataş",
                            Yas = 16
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
